@baseUrl = http://localhost:3333
@token = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "Marcos",
    "email": "marcos2@test.com",
    "password": "123"
}

###
# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "marcos2@test.com",
    "password": "123"
}

###
# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "How to use NestJS with Prisma?",
    "content": "I want to know how to use NestJS with Prisma. Can someone help me?" 
}